<a href="https://colab.research.google.com/github/Roshni-Rathore05/Pandas_Practice_file/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

data = {
    'emp_id':      [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    'name':        ['Ravi Kumar',    'Priya Sharma',  'Ankit Verma',   'Neha Singh',
                    'Rohit Gupta',   'Sunita Rao',    'Vikas Joshi',   'Meera Nair',
                    'Arjun Patel',   'Pooja Mishra',  'Ravi Kumar',    'Deepak Shah',
                    'Kavita Reddy',  'Suresh Iyer',   'Ankita Das',    'Mohit Sinha',
                    'Priya Sharma',  'Rajesh Yadav',  'Sneha Tiwari',  'Amit Pandey'],

    'dept':        ['Engineering', 'HR',          'Engineering', 'Finance',
                    'Marketing',   'Engineering', 'HR',          'Finance',
                    'Engineering', 'Marketing',   'Engineering', 'Finance',
                    'HR',          'Engineering', 'Marketing',   'Finance',
                    'HR',          'Engineering', 'Marketing',   'Engineering'],

    'city':        ['Delhi',    'Mumbai',    'Bangalore', 'Delhi',
                    'Mumbai',   'Bangalore', 'Chennai',   'Delhi',
                    'Mumbai',   'Bangalore', 'Delhi',     'Chennai',
                    'Mumbai',   'Bangalore', 'Delhi',     'Mumbai',
                    'Chennai',  'Bangalore', 'Delhi',     'Mumbai'],

    'salary':      [75000, 42000, 88000, 55000, 61000, 92000, 38000, 67000,
                    83000, 49000, 75000, 71000, 44000, 95000, 53000, 68000,
                    np.nan, 87000, 58000, 79000],

    'age':         [29, 34, 27, 31, 28, 35, 26, 33, 30, 25,
                    29, 38, 32, 40, 27, 36, 34, 31, 28, 33],

    'experience':  [5, 8, 3, 6, 4, 10, 2, 7, 6, 1,
                    5, 12, 7, 15, 3, 9, 8, 7, 4, 8],

    'rating':      [4.2, 3.8, 4.5, 3.5, 4.0, 4.8, 3.2, 4.1,
                    4.6, 3.9, 4.2, 4.3, 3.7, 4.9, np.nan, 4.0,
                    3.8, 4.7, 4.1, 4.4],

    'gender':      ['M', 'F', 'M', 'F', 'M', 'F', 'M', 'F',
                    'M', 'F', 'M', 'M', 'F', 'M', 'F', 'M',
                    'F', 'M', 'F', 'M'],

    'joining_year':[2019, 2016, 2021, 2018, 2020, 2014, 2022, 2017,
                    2018, 2023, 2019, 2012, 2017, 2009, 2021, 2015,
                    2016, 2017, 2020, 2016],

    'email':       ['ravi@tc.com',   'priya@tc.com',  'ankit@tc.com',  'neha@tc.com',
                    'rohit@tc.com',  'sunita@tc.com', 'vikas@tc.com',  'meera@tc.com',
                    'arjun@tc.com',  'pooja@tc.com',  'ravi2@tc.com',  'deepak@tc.com',
                    'kavita@tc.com', 'suresh@tc.com', 'ankita@tc.com', 'mohit@tc.com',
                    'priya2@tc.com', 'rajesh@tc.com', 'sneha@tc.com',  'amit@tc.com'],
}

df = pd.DataFrame(data)
print(df.shape)   # (20, 12)
print(df.dtypes)

(20, 11)
emp_id            int64
name             object
dept             object
city             object
salary          float64
age               int64
experience        int64
rating          float64
gender           object
joining_year      int64
email            object
dtype: object

In [ ]:
df.head(6)

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com

In [ ]:
df.isnull().sum().sum()

np.int64(2)

In [ ]:
df.describe()

          emp_id        salary        age  experience     rating  joining_year
count   20.00000     19.000000  20.000000    20.00000  19.000000      20.00000
mean   110.50000  67368.421053  31.300000     6.50000   4.142105    2017.50000
std      5.91608  17588.539597   4.079474     3.41051   0.446363       3.41051
min    101.00000  38000.000000  25.000000     1.00000   3.200000    2009.00000
25%    105.75000  54000.000000  28.000000     4.00000   3.850000    2016.00000
50%    110.50000  68000.000000  31.000000     6.50000   4.100000    2017.50000
75%    115.25000  81000.000000  34.000000     8.00000   4.450000    2020.00000
max    120.00000  95000.000000  40.000000    15.00000   4.900000    2023.00000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   emp_id        20 non-null     int64
 1   name          20 non-null     object
 2   dept          20 non-null     object
 3   city          20 non-null     object
 4   salary        19 non-null     float64
 5   age           20 non-null     int64
 6   experience    20 non-null     int64
 7   rating        19 non-null     float64
 8   gender        20 non-null     object
 9   joining_year  20 non-null     int64
 10  email         20 non-null     object
dtypes: float64(2), int64(4), object(5)
memory usage: 1.8+ KB

In [ ]:
eng=df[df["dept"]=="Engineering"]

In [ ]:
df[df["salary"]>70000]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com
11,112,Deepak Shah,Finance,Chennai,71000.0,38,12,4.3,M,2012,deepak@tc.com
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com

In [ ]:
df[df["age"]<30]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com
6,107,Vikas Joshi,HR,Chennai,38000.0,26,2,3.2,M,2022,vikas@tc.com
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com

In [ ]:
df[df["rating"] !=4.5]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com
6,107,Vikas Joshi,HR,Chennai,38000.0,26,2,3.2,M,2022,vikas@tc.com
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com
11,112,Deepak Shah,Finance,Chennai,71000.0,38,12,4.3,M,2012,deepak@tc.com
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com
15,116,Mohit Sinha,Finance,Mumbai,68000.0,36,9,4.0,M,2015,mohit@tc.com
16,117,Priya Sharma,HR,Chennai,NaN,34,8,3.8,F,2016,priya2@tc.com
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com

In [ ]:
df[(df["dept"]=="Engineering") & (df["salary"]>80000)]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com

In [ ]:
df[(df["city"]=="Mumbai") | (df["city"]=="Delhi")]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com
15,116,Mohit Sinha,Finance,Mumbai,68000.0,36,9,4.0,M,2015,mohit@tc.com
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com

In [ ]:
df[(df["gender"]=="F") & (df["rating"] <4.5)]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com
16,117,Priya Sharma,HR,Chennai,NaN,34,8,3.8,F,2016,priya2@tc.com
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com

In [ ]:
df[(df["dept"]=="Engineering") & (df["city"]=="Bangalore") & (df["experience"]>5)]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com

In [ ]:
df["dept"].value_counts()

dept
Engineering    8
HR             4
Finance        4
Marketing      4
Name: count, dtype: int64

In [ ]:
df["dept"].value_counts().sum()

np.int64(20)

In [ ]:
df["joining_year"].value_counts()

joining_year
2016    3
2017    3
2021    2
2019    2
2018    2
2020    2
2014    1
2022    1
2023    1
2012    1
2009    1
2015    1
Name: count, dtype: int64

In [ ]:
df["gender"].value_counts()

gender
M    11
F     9
Name: count, dtype: int64

In [ ]:
df[(df["experience"]<4) & (df["salary"]>50000)]

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com

In [ ]:
df.sort_values("salary",ascending=False)

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com
11,112,Deepak Shah,Finance,Chennai,71000.0,38,12,4.3,M,2012,deepak@tc.com
15,116,Mohit Sinha,Finance,Mumbai,68000.0,36,9,4.0,M,2015,mohit@tc.com
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com
6,107,Vikas Joshi,HR,Chennai,38000.0,26,2,3.2,M,2022,vikas@tc.com
16,117,Priya Sharma,HR,Chennai,NaN,34,8,3.8,F,2016,priya2@tc.com

In [ ]:
df.sort_values(["dept","salary","experience","age"],ascending=[True,False,True,True])

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com
11,112,Deepak Shah,Finance,Chennai,71000.0,38,12,4.3,M,2012,deepak@tc.com
15,116,Mohit Sinha,Finance,Mumbai,68000.0,36,9,4.0,M,2015,mohit@tc.com
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com
6,107,Vikas Joshi,HR,Chennai,38000.0,26,2,3.2,M,2022,vikas@tc.com
16,117,Priya Sharma,HR,Chennai,NaN,34,8,3.8,F,2016,priya2@tc.com
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com

In [ ]:
df['sal_rank'] = df['salary'].rank(ascending=False, method='dense')
df[['name', 'salary', 'sal_rank']].sort_values('sal_rank')

            name   salary  sal_rank
13   Suresh Iyer  95000.0       1.0
5     Sunita Rao  92000.0       2.0
2    Ankit Verma  88000.0       3.0
17  Rajesh Yadav  87000.0       4.0
8    Arjun Patel  83000.0       5.0
19   Amit Pandey  79000.0       6.0
0     Ravi Kumar  75000.0       7.0
10    Ravi Kumar  75000.0       7.0
11   Deepak Shah  71000.0       8.0
15   Mohit Sinha  68000.0       9.0
7     Meera Nair  67000.0      10.0
4    Rohit Gupta  61000.0      11.0
18  Sneha Tiwari  58000.0      12.0
3     Neha Singh  55000.0      13.0
14    Ankita Das  53000.0      14.0
9   Pooja Mishra  49000.0      15.0
12  Kavita Reddy  44000.0      16.0
1   Priya Sharma  42000.0      17.0
6    Vikas Joshi  38000.0      18.0
16  Priya Sharma      NaN       NaN

In [ ]:
df_idx=df.set_index("emp_id")
df_idx.loc[105]

name             Rohit Gupta
dept               Marketing
city                  Mumbai
salary               61000.0
age                       28
experience                 4
rating                   4.0
gender                     M
joining_year            2020
email           rohit@tc.com
sal_rank                11.0
Name: 105, dtype: object

In [ ]:
df_idx.reset_index()

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email,sal_rank
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com,7.0
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com,17.0
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com,3.0
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com,13.0
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com,11.0
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com,2.0
6,107,Vikas Joshi,HR,Chennai,38000.0,26,2,3.2,M,2022,vikas@tc.com,18.0
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com,10.0
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com,5.0
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com,15.0
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com,7.0
11,112,Deepak Shah,Finance,Chennai,71000.0,38,12,4.3,M,2012,deepak@tc.com,8.0
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com,16.0
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com,1.0
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com,14.0
15,116,Mohit Sinha,Finance,Mumbai,68000.0,36,9,4.0,M,2015,mohit@tc.com,9.0
16,117,Priya Sharma,HR,Chennai,NaN,34,8,3.8,F,2016,priya2@tc.com,NaN
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com,4.0
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com,12.0
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com,6.0

In [ ]:
df.rename(columns={"dept":"work"})

,emp_id,name,work,city,salary,age,experience,rating,gender,joining_year,email,sal_rank
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com,7.0
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com,17.0
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com,3.0
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com,13.0
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com,11.0
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com,2.0
6,107,Vikas Joshi,HR,Chennai,38000.0,26,2,3.2,M,2022,vikas@tc.com,18.0
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com,10.0
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com,5.0
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com,15.0
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com,7.0
11,112,Deepak Shah,Finance,Chennai,71000.0,38,12,4.3,M,2012,deepak@tc.com,8.0
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com,16.0
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com,1.0
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com,14.0
15,116,Mohit Sinha,Finance,Mumbai,68000.0,36,9,4.0,M,2015,mohit@tc.com,9.0
16,117,Priya Sharma,HR,Chennai,NaN,34,8,3.8,F,2016,priya2@tc.com,NaN
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com,4.0
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com,12.0
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com,6.0

In [ ]:
df["dept"].unique()

array(['Engineering', 'HR', 'Finance', 'Marketing'], dtype=object)

In [ ]:
df["dept"].nunique()

4

In [ ]:
print(df["city"].unique())
print(df["city"].nunique())

['Delhi' 'Mumbai' 'Bangalore' 'Chennai']
4

In [ ]:
df.isnull().sum()

emp_id          0
name            0
dept            0
city            0
salary          1
age             0
experience      0
rating          1
gender          0
joining_year    0
email           0
sal_rank        1
dtype: int64

In [ ]:
df["salary"].hasnans    # has nan values

True

dropna

how

1 any

2 all

subset

thresh

In [ ]:
# dlt nan row (exact) (Specifies a list of columns to look for missing values. Only rows with nulls in these specific columns will be dropped.)
df.dropna(subset="salary")

,emp_id,name,dept,city,salary,age,experience,rating,gender,joining_year,email
0,101,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi@tc.com
1,102,Priya Sharma,HR,Mumbai,42000.0,34,8,3.8,F,2016,priya@tc.com
2,103,Ankit Verma,Engineering,Bangalore,88000.0,27,3,4.5,M,2021,ankit@tc.com
3,104,Neha Singh,Finance,Delhi,55000.0,31,6,3.5,F,2018,neha@tc.com
4,105,Rohit Gupta,Marketing,Mumbai,61000.0,28,4,4.0,M,2020,rohit@tc.com
5,106,Sunita Rao,Engineering,Bangalore,92000.0,35,10,4.8,F,2014,sunita@tc.com
6,107,Vikas Joshi,HR,Chennai,38000.0,26,2,3.2,M,2022,vikas@tc.com
7,108,Meera Nair,Finance,Delhi,67000.0,33,7,4.1,F,2017,meera@tc.com
8,109,Arjun Patel,Engineering,Mumbai,83000.0,30,6,4.6,M,2018,arjun@tc.com
9,110,Pooja Mishra,Marketing,Bangalore,49000.0,25,1,3.9,F,2023,pooja@tc.com
10,111,Ravi Kumar,Engineering,Delhi,75000.0,29,5,4.2,M,2019,ravi2@tc.com
11,112,Deepak Shah,Finance,Chennai,71000.0,38,12,4.3,M,2012,deepak@tc.com
12,113,Kavita Reddy,HR,Mumbai,44000.0,32,7,3.7,F,2017,kavita@tc.com
13,114,Suresh Iyer,Engineering,Bangalore,95000.0,40,15,4.9,M,2009,suresh@tc.com
14,115,Ankita Das,Marketing,Delhi,53000.0,27,3,NaN,F,2021,ankita@tc.com
15,116,Mohit Sinha,Finance,Mumbai,68000.0,36,9,4.0,M,2015,mohit@tc.com
17,118,Rajesh Yadav,Engineering,Bangalore,87000.0,31,7,4.7,M,2017,rajesh@tc.com
18,119,Sneha Tiwari,Marketing,Delhi,58000.0,28,4,4.1,F,2020,sneha@tc.com
19,120,Amit Pandey,Engineering,Mumbai,79000.0,33,8,4.4,M,2016,amit@tc.com

dropna (handle missing & null values)

drop (dlt row & colmns)