<a href="https://colab.research.google.com/github/Roshni-Rathore05/Pandas_Practice_file/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# PANDAS
Pandas is a fast, powerful, flexible, and easy to use open source data analysis and manipulation tool, build on top of the python programming language.

# series
# from list
# from dict
# from nd array

SERIES
A Pandas series is like a column in table . it is a 1D array holding of any type

In [ ]:
# series from string (list)
import numpy as np
import pandas as pd
name=["roshni","chhaya","amanika","divyanshi"]
print(pd.Series(name))

0       roshni
1       chhaya
2      amanika
3    divyanshi
dtype: object

In [ ]:
# series from integer (list)
marks=[2,4,7,8,4,5,8]
pd.Series(marks)

0    2
1    4
2    7
3    8
4    4
5    5
6    8
dtype: int64

In [ ]:
# custom index
name=["roshni","chhaya","amanika","divyanshi"]
marks=[34,65,35,67]
pd.Series(marks,index=name)

roshni       34
chhaya       65
amanika      35
divyanshi    67
dtype: int64

In [ ]:
# name
import pandas as pd
name=["roshni","chhaya","amanika","divyanshi"]
marks=[34,65,35,67]
pd.Series(marks,index=name,name="marks")

roshni       34
chhaya       65
amanika      35
divyanshi    67
Name: marks, dtype: int64

In [ ]:
# series from dict
dict={"roshni":[2,4,6,4,6],"chhaya":[6,4,7,4,7],"divyanshi":[6,4,7,8,3]}
pd.Series(dict)

roshni       [2, 4, 6, 4, 6]
chhaya       [6, 4, 7, 4, 7]
divyanshi    [6, 4, 7, 8, 3]
dtype: object

In [ ]:
import numpy as np
# series from numpy array
arr=np.random.randint(0,10,4)
arr

array([6, 9, 5, 9])

In [ ]:
s=pd.Series(arr,index=["roshni","anamika","chhaya","divyanshi"],name="marks")
s

roshni       6
anamika      9
chhaya       5
divyanshi    9
Name: marks, dtype: int64

SERIES ATTRIBUTES

1.size()

2.dtype

3.name

4.index

5.is_unique

6.values

SERIES USING READ_CVS

WITH 1 COL

WITH 2 COL

In [28]:
import pandas as pd

# one col

df=pd.read_csv("/content/subs.csv")
type(df)
print(df.shape)
df.head(5)

(365, 1)

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [36]:
# convert dataframe into series using sqeeze
subs=pd.read_csv('subs.csv').squeeze("columns")
print(df.shape)
subs

(365, 1)

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [37]:
df.index

RangeIndex(start=0, stop=365, step=1)

In [27]:
# two col

movie=pd.read_csv("/content/bollywood.csv")
print(type(movie))
print(movie.shape)
movie

<class 'pandas.core.frame.DataFrame'>
(1500, 2)

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [39]:
movie=pd.read_csv("/content/bollywood.csv",index_col="movie").squeeze("columns")
print(type(movie))
print(movie.shape)
movie

<class 'pandas.core.series.Series'>
(1500,)

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [40]:
movie.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [41]:
movie.values

array(['Vicky Kaushal', 'Vicky Ahuja', 'Anupam Kher', ..., 'Vivek Oberoi',
       'Ajay Devgn', 'Akshay Kumar'], dtype=object)

In [43]:
movie.is_unique

False

SERIES METHODS

1. head & tail

2. sample

3. value_count-> movie

4. sort_values-> inplace

5. sort_index->inplace->movies

In [45]:
# randomly generate a row from dataset
# also we can select what we want to see using table filter
movie.sample()

movie
Aaj Ka Andha Kanoon    Sudesh Berry
Name: lead, dtype: object

In [49]:
movie.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [50]:
movie.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

In [51]:
movie.sort_values()

movie
Qaidi Band                            Aadar Jain
Roar: Tigers of the Sundarbans      Aadil Chahal
Lipstick Under My Burkha            Aahana Kumra
Raat Gayi Baat Gayi?                Aamir Bashir
Talaash: The Answer Lies Within       Aamir Khan
                                        ...
Dil Toh Deewana Hai                  Zeenat Aman
Sallu Ki Shaadi                      Zeenat Aman
Strings of Passion                   Zeenat Aman
Dunno Y... Na Jaane Kyon             Zeenat Aman
Taj Mahal: An Eternal Love Story     Zulfi Sayed
Name: lead, Length: 1500, dtype: object

SERIES MATH METHOD

count

sum

mean, mode,median, std, var

min/ max

describe

In [54]:
movie.count()

np.int64(1500)

In [55]:
subs.sum()

np.int64(49510)

In [57]:
subs.mean()

np.float64(135.64383561643837)

In [58]:
subs.mode()

0    105
Name: Subscribers gained, dtype: int64

In [59]:
subs.median()

123.0

In [60]:
subs.min()

33

In [61]:
subs.max()

396

In [62]:

print(subs.var())

subs.std()

3928.1585127201556

62.67502303725269

In [63]:
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [66]:
from re import sub
print(subs.info())
print(subs.shape)
print(subs.size)

<class 'pandas.core.series.Series'>
RangeIndex: 365 entries, 0 to 364
Series name: Subscribers gained
Non-Null Count  Dtype
--------------  -----
365 non-null    int64
dtypes: int64(1)
memory usage: 3.0 KB
None
(365,)
365

In [ ]:
# SERIES INDEXING

In [1]:
friends = ["Raj", "Simran", "Rahul", "Anjali", "Rohan", "Priya"]
friends[:3]

['Raj', 'Simran', 'Rahul']

In [3]:
friends[2:5]

['Rahul', 'Anjali', 'Rohan']

In [4]:
friends[-2:]

['Rohan', 'Priya']

In [3]:
a= ["3 Idiots", "DDLJ", "Sholay", "Dangal", "Lagaan", "PK"]
a[:3]

['3 Idiots', 'DDLJ', 'Sholay']

In [4]:
a[-3:]

['Dangal', 'Lagaan', 'PK']

In [18]:
fruits = ["Apple", "Banana", "Cherry", "Date", "Elderberry"]
fruits[-1]
fruits[len(fruits)-1]

'Elderberry'

In [19]:
score = [45, 67, 89, 23, 91, 56, 78]
score[-4:]
score[-0]

45

In [8]:
score[-3:-1]

[91, 56]

In [4]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[::2])
# reverse 7 to 1 step 2
# first slicing then reverse the slice
print(numbers[1:8:2][::-1])

# revese last 5 itmes

print(numbers[-5::2][::-1])

# Going backward from index 5 to 3
numbers[5:2:-1]

[0, 2, 4, 6, 8]
[7, 5, 3, 1]
[9, 7, 5]

[5, 4, 3]

In [10]:
numbers[::-1] #reverse entire list

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [12]:
numbers[1::2]

[1, 3, 5, 7, 9]

In [13]:
numbers[:6:2]

[0, 2, 4]

In [14]:
marks = [
    [85, 90, 78],  # Student 1: Maths, Science, English
    [92, 88, 95],  # Student 2
    [70, 85, 80]   # Student 3
]

marks[1][:2]

[92, 88]

In [15]:
marks[0,1,2][0,0,0]

TypeError: list indices must be integers or slices, not tuple

In [14]:
import numpy as np
img = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
img[0,0]

np.int64(10)

1. singe element access

2. Row/Column Extraction

3. Subregion (ROI - Region of Interest)

4. Advanced Indexing Techniques

    A) Boolean Indexing (Conditional Selection)

    B) Fancy Indexing (Integer Array Indexing)

    C) Mixed Boolean and Fancy Indexing

5. Advanced 2D Slicing Patterns

In [17]:
# [row,col]
# access single element
print(img[2,2])

print(img[-1,-1])
print(img[-1,2])

110
120
110

In [24]:
#  entire row
print(img[1])
print(img[2])

# entire column
print(img[:,2])

[50 60 70 80]
[ 90 100 110 120]
[ 30  70 110]

In [26]:
# multiple rows
print(img[0:2])

[[10 20 30 40]
 [50 60 70 80]]

In [28]:
# fancy indexing
print(img[[2,1]])
# Row 2 and row 1 (fancy indexing

[[ 90 100 110 120]
 [ 50  60  70  80]]

In [32]:
# Subregion (ROI - Region of Interest)
# Format: arr[row_start:row_end, col_start:col_end]

print(img[1:3,1:3])
print(img[-2:,-2:])

[[ 60  70]
 [100 110]]
[[ 70  80]
 [110 120]]

In [40]:
# Advanced Indexing Techniques
# A) Boolean Indexing (Conditional Selection)
arr = np.array([10, 25, 30, 45, 50, 65])

marks=arr>30
print(marks)
print(arr[marks])

# in short hand
print(arr[arr>30])

[False False False  True  True  True]
[45 50 65]
[45 50 65]

In [52]:
# B) Fancy Indexing (Integer Array Indexing)
arr = np.array([10, 20, 30, 40, 50])
# error though
# print(arr[0,2,4]

# solve
indices=[0,2,4]
arr[indices]

array([10, 30, 50])

In [59]:
# 2d fancy indexing
img = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
# specific row
print("spacific rows ",img[[2,1]])

# select spefic elements

row=[1,2,2]
col=[1,0,2]
img[row,col]

spacific rows  [[70 80 90]
 [40 50 60]]

array([50, 70, 90])

In [79]:
img = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])
# Every other row
print(img[::2])
print()

# Every other col

print()

# Every other col of Every other row
print(img[::2,::2])
print()

# col 1&2
a=img[:,0:2]
print(a)
print()

# Reverse columns (flip horizontally)



# Reverse rows (flip vertically)
print(img[::2][::-1])
print()

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


[[ 1  3  5]
 [11 13 15]]

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]

[[ 1]
 [ 6]
 [11]
 [16]]
[[11 12 13 14 15]
 [ 1  2  3  4  5]]

SERIES INDEXING

Using .loc (Label-based)

Using .iloc (Position-based)

In [83]:
import pandas as pd
scores = pd.Series([85, 92, 78, 95, 88],index=['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],name="marks")
scores

Alice      85
Bob        92
Charlie    78
Diana      95
Eve        88
Name: marks, dtype: int64

In [92]:
# using .loc (label based)

# single element
print(scores.loc["Alice"])
print()

# multi ele
print(scores.loc[["Bob","Eve"]])
print()

# slicing by labels[inclusive]
print(scores.loc["Charlie":"Eve"])
print()

# Boolean condition
print(scores.loc[scores>90])

85

Bob    92
Eve    88
Name: marks, dtype: int64

Charlie    78
Diana      95
Eve        88
Name: marks, dtype: int64

Bob      92
Diana    95
Name: marks, dtype: int64

In [110]:
# Using .iloc (Position-based)

# Single element by position
print(scores.iloc[1])

print()

# multiple
print(scores.iloc[[0,4]])
print()

# Slicing by position (EXCLUSIVE end!)
print(scores.iloc[1:4])
print()
# negative indexing
print(scores.iloc[-4:-2])
print()
# reverse
print(scores.iloc[-4:][::-1])

92

Alice    85
Eve      88
Name: marks, dtype: int64

Bob        92
Charlie    78
Diana      95
Name: marks, dtype: int64

Bob        92
Charlie    78
Name: marks, dtype: int64

Eve        88
Diana      95
Charlie    78
Bob        92
Name: marks, dtype: int64

DATA FRAME

.loc - Label-based Selection

.ILOC - POSITION BASED SELECTION

In [4]:
import pandas as pd
# Student grades dataset
data = {
    'Math': [85, 92, 78, 95, 88],
    'Science': [90, 88, 85, 98, 91],
    'English': [88, 85, 92, 90, 87]
}
df = pd.DataFrame(data,
                  index=['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])
print(df)
df.shape

         Math  Science  English
Alice      85       90       88
Bob        92       88       85
Charlie    78       85       92
Diana      95       98       90
Eve        88       91       87

(5, 3)

In [124]:
# .loc - Label-based Selection

# Single cell (row_label, column_label)
print(df.loc["Charlie","Science"])

# entire row
print(df.loc["Charlie"])
print()

# entire col
print(df.loc[:,"Science"])
print()
# multiple rows
print(df.loc[["Alice","Eve"]])
print()

# # multiple col
print(df.loc[:,["Math","English"]])

# Subregion (rows + columns)
print(df.loc["Bob":"Diana","Science":"English"])

85
Math       78
Science    85
English    92
Name: Charlie, dtype: int64

Alice      90
Bob        88
Charlie    85
Diana      98
Eve        91
Name: Science, dtype: int64

       Math  Science  English
Alice    85       90       88
Eve      88       91       87

         Math  English
Alice      85       88
Bob        92       85
Charlie    78       92
Diana      95       90
Eve        88       87
         Science  English
Bob           88       85
Charlie       85       92
Diana         98       90

In [8]:
# chnage value
df[["Alice","Math"]]=80
df

         Math  Science  English  Alice
Alice      80       90       88     80
Bob        80       88       85     80
Charlie    80       85       92     80
Diana      80       98       90     80
Eve        80       91       87     80

In [12]:
# delete alice col
df.drop(columns=["Alice"])

         Math  Science  English
Alice      80       90       88
Bob        80       88       85
Charlie    80       85       92
Diana      80       98       90
Eve        80       91       87

In [16]:
# add row
df.loc[len(df)]={"Math":45,"Science":55,"English":34}
df

         Math  Science  English  Alice
Alice      80       90       88   80.0
Bob        80       88       85   80.0
Charlie    80       85       92   80.0
Diana      80       98       90   80.0
Eve        80       91       87   80.0
5          45       55       34    NaN

In [21]:
# delete alice col
df.drop(columns=["Alice"],inplace=True)

KeyError: "['Alice'] not found in axis"

In [22]:
df=df.rename(index={5:"roshni"})
df

         Math  Science  English
Alice      80       90       88
Bob        80       88       85
Charlie    80       85       92
Diana      80       98       90
Eve        80       91       87
roshni     45       55       34

In [23]:
df

         Math  Science  English
Alice      80       90       88
Bob        80       88       85
Charlie    80       85       92
Diana      80       98       90
Eve        80       91       87
roshni     45       55       34

         Math  Science  English
Alice     NaN      NaN      NaN
Bob       NaN      NaN      NaN
Charlie   NaN      NaN      NaN
Diana    80.0     98.0     90.0
Eve      80.0     91.0     87.0
roshni   45.0     55.0     34.0

In [32]:
df.loc[["Alice","roshni"],"Math"]=45,35
df

         Math  Science  English
Alice    45.0      NaN      NaN
Bob       NaN      NaN      NaN
Charlie   NaN      NaN      NaN
Diana    80.0     98.0     90.0
Eve      80.0     91.0     87.0
roshni   35.0     55.0     34.0

In [35]:
print(dir(df))

['English', 'Math', 'Science', 'T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [44]:
name=["roshni","chhaya","amanika","divyanshi"]
s=pd.Series(name)
s

0       roshni
1       chhaya
2      amanika
3    divyanshi
dtype: object

In [45]:
# type conversion
type(list(s))

list

In [50]:
# membership operator
"roshni" in name   #value not index

True

In [48]:
# for loop
for i in df:
  print(i)  #give col name

Math
Science
English

In [51]:
# arithmetic operation
marks=[34,64,64,34,65,35]
marks=pd.Series(marks)
marks

0    34
1    64
2    64
3    34
4    65
5    35
dtype: int64

In [65]:
# arithmetic operation

# shape (tuple)  (n_rows,) &(n_row,n_col)  Best for checking row/column counts.
# size (ineteger)  (n_rows)(n_row*n_col)  Best for finding the total data volume.
print(marks[marks>60].size)
print(100-marks)

3
0    66
1    36
2    36
3    66
4    35
5    65
dtype: int64

In [66]:
movie=pd.read_csv("/content/movies.csv")
df

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [67]:
movie.head(5)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [68]:
print(movie.shape)
movie.size

(1629, 18)

29322

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [72]:
movie.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [77]:
movie.isnull()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1625,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1626,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True
1627,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1628,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

In [78]:
# total null values
print(movie.isnull().sum)

# col wise null values
movie.isnull().sum()

<bound method DataFrame.sum of       title_x  imdb_id  poster_path  wiki_link  title_y  original_title  \
0       False    False        False      False    False           False
1       False    False         True      False    False           False
2       False    False        False      False    False           False
3       False    False        False      False    False           False
4       False    False         True      False    False           False
...       ...      ...          ...        ...      ...             ...
1624    False    False        False      False    False           False
1625    False    False        False      False    False           False
1626    False    False         True      False    False           False
1627    False    False        False      False    False           False
1628    False    False        False      False    False           False

      is_adult  year_of_release  runtime  genres  imdb_rating  imdb_votes  \
0        False            False    False   False        False       False
1        False            False    False   False        False       False
2        False            False    False   False        False       False
3        False            False    False   False        False       False
4        False            False    False   False        False       False
...        ...              ...      ...     ...          ...         ...
1624     False            False    False   False        False       False
1625     False            False    False   False        False       False
1626     False            False    False   False        False       False
1627     False            False    False   False        False       False
1628     False            False    False   False        False       False

      story  summary  tagline  actors  wins_nominations  release_date
0     False    False     True   False             False         False
1     False    False     True   False              True         False
2     False    False     True   False              True         False
3     False    False     True   False              True         False
4     False    False     True   False             False         False
...     ...      ...      ...     ...               ...           ...
1624  False    False     True   False              True         False
1625  False    False     True   False              True         False
1626  False    False     True   False              True          True
1627  False    False     True   False              True         False
1628  False    False     True   False              True         False

[1629 rows x 18 columns]>

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [79]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [80]:
# we can also check null values using info()
1629-1526

103

In [83]:
# duplicate
movie.duplicated().sum()

np.int64(0)

In [97]:
student=pd.DataFrame([[2,4,7],[4,3,7],[0,0,0],[0,0,0]],index=["math","hindi","english","sst"])
print(student)
student.duplicated().sum()

         0  1  2
math     2  4  7
hindi    4  3  7
english  0  0  0
sst      0  0  0

np.int64(1)

In [100]:
# rename
# df=df.rename(index={5:"roshni"})
student.rename(columns={0:"roshni",1:"chhaya",2:"anamika"},inplace=True)
student

         roshni  chhaya  anamika
math          2       4        7
hindi         4       3        7
english       0       0        0
sst           0       0        0

In [ ]:
# mathematics